---
name: release

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      # Required to be able to push docker manifests
      DOCKER_CLI_EXPERIMENTAL: 'enabled'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and publish the images
        run: |
          export TAG=${GITHUB_REF##*/}
          docker buildx build --push \
            --tag docker.io/mvisonneau/generatedata:${TAG/main/latest} \
            --tag ghcr.io/mvisonneau/generatedata:${TAG/main/latest} \
            --platform linux/amd64,linux/arm64 \
            .
